### ISSUE TITLE
Hope to support finding assembly code

### ISSUE THREAD

**Issue by XMDS** [ThirteenAG/Hooking.Patterns#10]
For example pattern("mov eax, ebx")

**Comment by ThirteenAG** [comment]
I think you can do that with https://github.com/cursey/kananlib
Outside of scope of this project.

**Comment by XMDS** [comment]
@ThirteenAG  
Why not implement it?  I have a very streamlined solution that requires no third-party libraries.  The writer only needs to pass a naked inline assembly function pointer, and then we only need to use memcpy to copy the bytes and convert them to string form to achieve it.  This can be done using standard C language inline assembly syntax

**Comment by ThirteenAG** [comment]
You can do it in a fork. Like I said, this repository is only for this specific task, and it's a dependency for other repositories.
